version: '3.8'
services:
  app:
    container_name: web
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5005:5005"
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 